repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen 
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''
    hooks:
      - id: autopep8