name: CI Workflow 

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --with dev
    
      - name: Run tests
        run: poetry run pytest